# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }


gem "rubocop", "~> 1.68.0"

gem "rubocop-github", "~> 0.20.0"


gem "rubocop-performance", "~>1.21.1"


gem "rubocop-rails", "~> 2.5"
gem "rubocop-rspec", "~> 3.0.0"